/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as ApiInterviewRouteImport } from './routes/api/interview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewRoute = ApiInterviewRouteImport.update({
  id: '/api/interview',
  path: '/api/interview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidates': typeof CandidatesRoute
  '/api/interview': typeof ApiInterviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidates': typeof CandidatesRoute
  '/api/interview': typeof ApiInterviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidates': typeof CandidatesRoute
  '/api/interview': typeof ApiInterviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/candidates' | '/api/interview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/candidates' | '/api/interview'
  id: '__root__' | '/' | '/candidates' | '/api/interview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidatesRoute: typeof CandidatesRoute
  ApiInterviewRoute: typeof ApiInterviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview': {
      id: '/api/interview'
      path: '/api/interview'
      fullPath: '/api/interview'
      preLoaderRoute: typeof ApiInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidatesRoute: CandidatesRoute,
  ApiInterviewRoute: ApiInterviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
